import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { ROUTE_META, SEARCH_EXCLUDE, type SearchEntry } from "../app/_lib/search-meta";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");
const APP_DIR = join(ROOT, "app");
const OUT_FILE = join(APP_DIR, "_lib/search-index.generated.ts");

const EXCLUDED_DIRS = new Set(["_lib", "_components", "api"]);

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry)) results.push(...walk(full));
    } else if (entry === "page.tsx") {
      results.push(full);
    }
  }
  return results;
}

function deriveRoute(pagePath: string): string {
  const rel = relative(APP_DIR, pagePath);
  if (rel === "page.tsx") return "/";
  const dir = rel.replace(/\/page\.tsx$/, "");
  const parts = dir.split("/").filter((p) => !p.startsWith("("));
  return parts.length === 0 ? "/" : "/" + parts.join("/");
}

function extractMetaBlock(text: string): string {
  const idx = text.indexOf("export const metadata");
  if (idx === -1) return "";
  const brace = text.indexOf("{", idx);
  if (brace === -1) return "";
  let depth = 0;
  for (let i = brace; i < text.length; i++) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}") { depth--; if (depth === 0) return text.slice(brace, i + 1); }
  }
  return "";
}

function extractTitle(text: string, route: string): string {
  const block = extractMetaBlock(text);
  const m = block.match(/\btitle\s*:\s*"((?:[^"\\]|\\[\s\S])*)"/);
  // Strip site suffix — only em-dash/en-dash to avoid stripping hyphenated words
  if (m) return m[1].replace(/\s*[—–].*$/i, "").trim();
  if (route === "/") return "Home";
  return route
    .slice(1)
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

function extractDescription(text: string): string {
  const block = extractMetaBlock(text);
  const m = block.match(/\bdescription\s*:\s*"((?:[^"\\]|\\[\s\S])*)"/);
  if (!m) return "";
  return m[1].replace(/\s+/g, " ").trim();
}

function extractAnchors(text: string): string[] {
  const seen = new Set<string>();
  for (const m of text.matchAll(/\bid="([a-z][a-z0-9-]*)"/g)) seen.add(m[1]);
  for (const m of text.matchAll(/\bid=\{"([a-z][a-z0-9-]*)"\}/g)) seen.add(m[1]);
  return [...seen];
}

function toTitleCase(str: string): string {
  return str
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

const pageFiles = walk(APP_DIR);
const generatedRoutes = new Set(pageFiles.map(deriveRoute));

for (const route of Object.keys(ROUTE_META)) {
  if (!generatedRoutes.has(route) && !SEARCH_EXCLUDE.includes(route)) {
    console.warn(`⚠️  search-meta.ts has entry for "${route}" but no page.tsx found — may be stale.`);
  }
}

const entries: SearchEntry[] = [];

for (const pageFile of pageFiles) {
  const route = deriveRoute(pageFile);
  if (SEARCH_EXCLUDE.includes(route)) continue;

  const text = readFileSync(pageFile, "utf-8");
  const meta = ROUTE_META[route] ?? {};

  const title = extractTitle(text, route);
  const description = meta.description ?? extractDescription(text);
  const group = meta.group ?? "Pages";

  entries.push({
    title,
    description,
    href: route,
    ...(meta.keywords ? { keywords: meta.keywords } : {}),
    group,
  });

  const sectionLabels = meta.sectionLabels;
  // Whitelist mode: when sectionLabels is defined, only those anchor IDs appear.
  // Auto mode: when sectionLabels is undefined, all static id="..." anchors appear.
  const anchorIds = sectionLabels
    ? Object.keys(sectionLabels)
    : extractAnchors(text);

  for (const id of anchorIds) {
    const label = sectionLabels?.[id] ?? toTitleCase(id);
    entries.push({ title: label, description: "", href: `${route}#${id}`, group });
  }
}

const out = [
  `// AUTO-GENERATED by scripts/generate-search-index — do not edit by hand. Run: npm run build:search`,
  `import type { SearchEntry } from "./search-meta";`,
  ``,
  `export const GENERATED_SEARCH_INDEX: SearchEntry[] = ${JSON.stringify(entries, null, 2)};`,
  ``,
].join("\n");

writeFileSync(OUT_FILE, out, "utf-8");

const includedRoutes = [...generatedRoutes].filter((r) => !SEARCH_EXCLUDE.includes(r));
console.log(`✅ Search index generated`);
console.log(`   Routes: ${includedRoutes.length}`);
console.log(`   Total entries: ${entries.length}`);
