// AUTO-GENERATED by scripts/generate-search-index — do not edit by hand. Run: npm run build:search
import type { SearchEntry } from "./search-meta";

export const GENERATED_SEARCH_INDEX: SearchEntry[] = [
  {
    "title": "Android Studio Setup",
    "description": "A step-by-step walkthrough of installing Android Studio, opening the FtcRobotController project, and deploying your first build to a Control Hub.",
    "href": "/android-studio",
    "keywords": [
      "ide",
      "install",
      "gradle",
      "apk",
      "deploy",
      "control hub",
      "ftcrobotcontroller",
      "sdk"
    ],
    "group": "Guides"
  },
  {
    "title": "Installation Steps",
    "description": "",
    "href": "/android-studio#steps",
    "group": "Guides"
  },
  {
    "title": "Wireless ADB Setup",
    "description": "",
    "href": "/android-studio#wireless-adb",
    "group": "Guides"
  },
  {
    "title": "Blocks",
    "description": "A quick overview of FTC Blocks, the drag-and-drop programming tool it's pretty much like Scratch if you ever have used it. It's built into the Rev Hardware Client for teams getting started without Java and new to programming.",
    "href": "/blocks",
    "keywords": [
      "drag-and-drop",
      "visual",
      "scratch",
      "beginner",
      "rev hardware client",
      "no java",
      "opmode"
    ],
    "group": "Guides"
  },
  {
    "title": "What is Blocks",
    "description": "",
    "href": "/blocks#what-it-is",
    "group": "Guides"
  },
  {
    "title": "Command-Based Architecture",
    "description": "Educational guidance and architectural recommendations for organizing FTC robot code with the command-based pattern.",
    "href": "/command-based",
    "keywords": [
      "subsystem",
      "command",
      "scheduler",
      "trigger",
      "nextftc",
      "ivy",
      "solverslib",
      "wpilib",
      "frc",
      "scalable"
    ],
    "group": "Guides"
  },
  {
    "title": "Core Concepts",
    "description": "",
    "href": "/command-based#concepts",
    "group": "Guides"
  },
  {
    "title": "Library References",
    "description": "",
    "href": "/command-based#references",
    "group": "Guides"
  },
  {
    "title": "Contact",
    "description": "Get in touch with FTC Wires — ftcwires@gmail.com",
    "href": "/contact",
    "keywords": [
      "email",
      "reach",
      "contributors",
      "hazmat"
    ],
    "group": "Pages"
  },
  {
    "title": "Git Setup for FTC",
    "description": "A step-by-step guide to setting up Git and GitHub for FTC teams — create an account, install Git, fork the FtcRobotController, and clone it straight into Android Studio without ever touching the command line.",
    "href": "/git",
    "keywords": [
      "git",
      "github",
      "version control",
      "fork",
      "clone",
      "android studio",
      "ftcrobotcontroller"
    ],
    "group": "Guides"
  },
  {
    "title": "Setup Steps",
    "description": "",
    "href": "/git#steps",
    "group": "Guides"
  },
  {
    "title": "Troubleshooting",
    "description": "",
    "href": "/git#troubleshooting",
    "group": "Guides"
  },
  {
    "title": "Outreach",
    "description": "Per-event team spotlights from Wisconsin FTC. Each event is tagged with the FTC judged awards it helps your team build a case for.",
    "href": "/outreach",
    "keywords": [
      "events",
      "community",
      "awards",
      "inspire",
      "connect",
      "spotlights"
    ],
    "group": "Pages"
  },
  {
    "title": "Award Legend",
    "description": "",
    "href": "/outreach#award-legend",
    "group": "Pages"
  },
  {
    "title": "Team Spotlights",
    "description": "",
    "href": "/outreach#spotlights",
    "group": "Pages"
  },
  {
    "title": "Home",
    "description": "FTC WI.R.E.S. — Wisconsin Rises to Enable STEM Growth. Software guides, resources, and outreach spotlights for FTC teams.",
    "href": "/",
    "keywords": [
      "home",
      "wires",
      "wisconsin",
      "ftc",
      "hazmat",
      "13201",
      "stem"
    ],
    "group": "Pages"
  },
  {
    "title": "Parts Lending Network",
    "description": "An upcoming statewide lending pool for FTC hardware. Join the early access list.",
    "href": "/parts-lending-network",
    "keywords": [
      "borrow",
      "lend",
      "hardware",
      "waitlist",
      "parts",
      "motors"
    ],
    "group": "Pages"
  },
  {
    "title": "Pedro Pathing",
    "description": "A quick overview of Pedro Pathing, an FTC pathing library used for building autonomous routines.",
    "href": "/pedro-pathing",
    "keywords": [
      "bezier",
      "path following",
      "predictive braking",
      "follower",
      "ivy",
      "nextftc",
      "curves",
      "mecanum"
    ],
    "group": "Guides"
  },
  {
    "title": "What is Pedro Pathing",
    "description": "",
    "href": "/pedro-pathing#what-it-is",
    "group": "Guides"
  },
  {
    "title": "Planning",
    "description": "Season roadmaps, communication frameworks, and sponsorship playbooks for FTC teams.",
    "href": "/planning",
    "keywords": [
      "season",
      "roadmap",
      "communication",
      "burnout",
      "cadence"
    ],
    "group": "Pages"
  },
  {
    "title": "Register",
    "description": "Register your team to access FTC Wires software platform instructions and software platform resources.",
    "href": "/register",
    "keywords": [
      "sign up",
      "team number",
      "access",
      "guides",
      "auto",
      "autonomous"
    ],
    "group": "Pages"
  },
  {
    "title": "Resources",
    "description": "Hardware, software, game strategy, important sites, team info, and collaborative documents for Wisconsin FTC teams.",
    "href": "/resources",
    "keywords": [
      "links",
      "tools",
      "hardware",
      "software",
      "community",
      "strategy"
    ],
    "group": "Resources"
  },
  {
    "title": "Important Sites",
    "description": "",
    "href": "/resources#important-sites",
    "group": "Resources"
  },
  {
    "title": "Team Info",
    "description": "",
    "href": "/resources#team-info",
    "group": "Resources"
  },
  {
    "title": "Community & Collaboration",
    "description": "",
    "href": "/resources#collaborate",
    "group": "Resources"
  },
  {
    "title": "General Resources",
    "description": "",
    "href": "/resources#general",
    "group": "Resources"
  },
  {
    "title": "Hardware Resources",
    "description": "",
    "href": "/resources#hardware",
    "group": "Resources"
  },
  {
    "title": "Software Resources",
    "description": "",
    "href": "/resources#software",
    "group": "Resources"
  },
  {
    "title": "Game Strategy",
    "description": "",
    "href": "/resources#game-strategy",
    "group": "Resources"
  },
  {
    "title": "Roadrunner",
    "description": "A quick overview of Roadrunner, a motion planning library used by FTC teams for accurate and smooth autonomous navigation.",
    "href": "/roadrunner",
    "keywords": [
      "motion planning",
      "trajectory",
      "spline",
      "mecanum",
      "tank drive",
      "feedforward",
      "acme"
    ],
    "group": "Guides"
  },
  {
    "title": "What is Roadrunner",
    "description": "",
    "href": "/roadrunner#what-it-is",
    "group": "Guides"
  },
  {
    "title": "Software Examples & Guides",
    "description": "Curated examples, walkthroughs, and templates for the software FTC teams already use — Roadrunner, Pedro Pathing, Blocks, the FTC SDK, Android Studio setup, and command-based architecture.",
    "href": "/software-platform",
    "keywords": [
      "guides",
      "tools",
      "programming",
      "overview",
      "auto",
      "autonomous"
    ],
    "group": "Guides"
  },
  {
    "title": "Software Tools",
    "description": "",
    "href": "/software-platform#tools",
    "group": "Guides"
  },
  {
    "title": "Sponsorship",
    "description": "Grants, discounts, and sponsorship resources for Wisconsin FTC teams, plus a sample sponsorship letter.",
    "href": "/sponsorship",
    "keywords": [
      "funding",
      "money",
      "sponsors",
      "grants",
      "support"
    ],
    "group": "Sponsorship"
  },
  {
    "title": "How to Get Sponsors",
    "description": "",
    "href": "/sponsorship#how-to",
    "group": "Sponsorship"
  },
  {
    "title": "Grants & Discounts",
    "description": "",
    "href": "/sponsorship#grants",
    "group": "Sponsorship"
  },
  {
    "title": "Sample Sponsorship Letter",
    "description": "",
    "href": "/sponsorship#letter",
    "group": "Sponsorship"
  }
];
